### ISSUE TITLE
视频抽帧错误

### ISSUE THREAD

**Issue by yuzuo** [zap200281/PLabel#1]
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "duration" is null
	at com.pcl.util.VideoUtil.getIntSecond(VideoUtil.java:249) ~[classes!/:0.0.1-SNAPSHOT]
	at com.pcl.util.VideoUtil.getExceetTime(VideoUtil.java:239) ~[classes!/:0.0.1-SNAPSHOT]
	at com.pcl.service.DataSetService.runChouZhen(DataSetService.java:450) ~[classes!/:0.0.1-SNAPSHOT]
	at com.pcl.service.DataSetService.lambda$chouZhen$2(DataSetService.java:396) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by zap200281** [comment]
视频抽帧是需要ffmpeg，这个是在docker镜像中安装了ffmpeg，你有下载么？

**Comment by zap200281** [comment]
你好，这个你安装docker镜像了吗？ 抽帧需要ffmpeg支持。













At 2021-01-22 16:50:31, "yuzuo" <notifications@github.com> wrote:

java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "duration" is null
at com.pcl.util.VideoUtil.getIntSecond(VideoUtil.java:249) ~[classes!/:0.0.1-SNAPSHOT]
at com.pcl.util.VideoUtil.getExceetTime(VideoUtil.java:239) ~[classes!/:0.0.1-SNAPSHOT]
at com.pcl.service.DataSetService.runChouZhen(DataSetService.java:450) ~[classes!/:0.0.1-SNAPSHOT]
at com.pcl.service.DataSetService.lambda$chouZhen$2(DataSetService.java:396) ~[classes!/:0.0.1-SNAPSHOT]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by yuzuo** [comment]
嗯，可以了，tks



在 2021-01-28 10:32:10，"邹安平" <notifications@github.com> 写道：

你好，这个你安装docker镜像了吗？ 抽帧需要ffmpeg支持。













At 2021-01-22 16:50:31, "yuzuo" <notifications@github.com> wrote:

java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "duration" is null
at com.pcl.util.VideoUtil.getIntSecond(VideoUtil.java:249) ~[classes!/:0.0.1-SNAPSHOT]
at com.pcl.util.VideoUtil.getExceetTime(VideoUtil.java:239) ~[classes!/:0.0.1-SNAPSHOT]
at com.pcl.service.DataSetService.runChouZhen(DataSetService.java:450) ~[classes!/:0.0.1-SNAPSHOT]
at com.pcl.service.DataSetService.lambda$chouZhen$2(DataSetService.java:396) ~[classes!/:0.0.1-SNAPSHOT]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by zap200281** [comment]
启动镜像。
